# Generated by Django 4.2.4 on 2023-08-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Number', models.IntegerField(max_length=15)),
                ('Date', models.DateField()),
                ('Person', models.IntegerField(max_length=2)),
            ],
        ),
    ]
