# Generated by Django 4.2.4 on 2023-09-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_alter_book_table_number_alter_book_table_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=55)),
                ('Last_Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Username', models.CharField(max_length=55)),
                ('Password', models.CharField(max_length=55)),
            ],
        ),
    ]
