# Generated by Django 4.2.4 on 2023-09-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0003_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
