# Generated by Django 4.2.4 on 2023-09-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0004_rename_employee_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=55)),
                ('Decription', models.TextField(max_length=250)),
                ('Price', models.IntegerField()),
                ('Image', models.FileField(default=None, max_length=250, null=True, upload_to='items_image/')),
            ],
        ),
    ]
