# Generated by Django 4.2.4 on 2023-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0005_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
