# Generated by Django 4.2.4 on 2023-09-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0006_employees_coins_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Type',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
