# Generated by Django 4.2.4 on 2023-09-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0008_alter_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
