# Generated by Django 4.2.4 on 2023-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0010_carditems_itemsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditems',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
