# Generated by Django 4.2.4 on 2023-09-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0011_carditems_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='carditems',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
