# Generated by Django 4.2.4 on 2023-09-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0012_carditems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditems',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
