# Generated by Django 4.2.4 on 2023-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0013_alter_carditems_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsorder',
            name='UserId',
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='Username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
