# Generated by Django 4.2.4 on 2023-09-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0014_remove_itemsorder_userid_itemsorder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Coins',
            field=models.IntegerField(default=100),
        ),
    ]
